name       : gcovr
version    : '5.1'
release    : 5
source     :
    - https://github.com/gcovr/gcovr/archive/refs/tags/5.1.tar.gz : c2e3ba82fd526aec4109712ff4fa84041ea3a13c34877a1638165e8f9f4d76bc
license    : BSD-3-Clause
component  : programming.tools
summary    : Management tool for GNU gcov
description: |
    Gcovr provides a utility for managing the use of the GNU gcov utility and generating summarized code coverage results.
build      : |
    %python3_setup
install    : |
    %python3_install
