name       : gcovr
version    : 3.3
release    : 1
source     :
    - https://github.com/gcovr/gcovr/archive/3.3.tar.gz : 8a60ba6242d67a58320e9e16630d80448ef6d5284fda5fb3eff927b63c8b04a2
license    : BSD-3-Clause
component  : programming.tools
summary    : Management tool for GNU gcov
description: |
    Gcovr provides a utility for managing the use of the GNU gcov utility and generating summarized code coverage results.
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
