name       : gcovr
version    : '4.1'
release    : 2
source     :
    - https://github.com/gcovr/gcovr/archive/4.1.tar.gz : 1ad8042fd4dc4c355fd7e605d395eefa2a59b1677dfdc308e0ef00083e8b37ee
license    : BSD-3-Clause
component  : programming.tools
summary    : Management tool for GNU gcov
description: |
    Gcovr provides a utility for managing the use of the GNU gcov utility and generating summarized code coverage results.
build      : |
    %python3_setup
install    : |
    %python3_install
